export { onlyNumbers } from './only-numbers';
export { onlyLetters } from './only-letters';
export { formatPrice } from './format-currency';
export { isLastChar } from './is-last-char';
export { isValidCEP } from './is-valid-cep';
export { getCardType } from './get-card-type';
export { dateFormatted } from './format-date';
export { dateHourFormatted } from './format-date-hour';
export { getWindowDimensions } from './get-window-dimensions';
